MAJOR_MINOR_VERSION=`cat VERSION`
LATEST_VERSION_COMMIT=`git rev-list -1 main VERSION`
PATCH_VERSION=`git rev-list --count ${LATEST_VERSION_COMMIT}..main`
FULL_VERSION=${MAJOR_MINOR_VERSION}.${PATCH_VERSION}
OUTPUT_PATH = ${PUBLISH_DIRECTORY}/${FULL_VERSION}

if [-ne $OUTPUT_PATH]
then
  mkdir -p $OUTPUT_PATH
fi

dotnet publish -o $OUTPUT_PATH
